title: Coding at Sixty
author: Troy Womack
email: troy.feenix@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning something new as an old man

# social links
twitter_username: troy_womack
github_username:  troyfeenix

show_excerpts: true # set to false to remove excerpts on the homepage
